apiVersion: v1
kind: ServiceAccount
metadata:
  name: self-healing-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: self-healing-operator
rules:
- apiGroups: [""]
  resources:
  - pods
  - pods/log
  verbs: ["get", "list", "watch", "delete"]
- apiGroups: ["apps"]
  resources:
  - deployments
  - deployments/scale
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: [""]
  resources:
  - events
  verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: self-healing-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: self-healing-operator
subjects:
- kind: ServiceAccount
  name: self-healing-operator
  namespace: default 